apiVersion: 1

datasources:
  - name: InfluxDB Seedy
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: influxdb_seedy
    jsonData:
      version: Flux
      organization: neofarm
      defaultBucket: seedy_iot
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    editable: true
    isDefault: true
